### ISSUE TITLE
Confusion on sign of inequality

### ISSUE THREAD

**Issue by vishalmhjn** [andim/noisyopt#15]
First of all, Thank you for sharing your work.

I have a minor confusion at one location in the code. In https://github.com/andim/noisyopt/blob/625b874918ac5926c3bf05d869e914cbddfffe20/noisyopt/main.py#L204

I might be wrong, but just wanted to be sure if the sign of inequality be reversed, and instead be 
```(funcm(xtest) > funcm(x)+feps)) ```, since we are checking for non-improvement.

Thanks in advance.

**Comment by andim** [comment]
Thanks for your close reading of the code and your comment! It took me a bit to remind myself of the logic, but here is how it goes: This line checks for a case where function values are roughly equal between x and xtest. (Note that because this is within the elif clause, we have already checked that it is not smaller than f(x)-feps.) In this case, the step size might be to large and take xtest beyond the local minimum and we thus test whether taking a half step improves the function value.
